--- libpaho_embed_mqtt/Makefile.orig	2014-10-29 18:16:57.958053488 -0700
+++ libpaho_embed_mqtt/Makefile	2014-10-29 18:29:25.912439224 -0700
@@ -91,6 +91,8 @@
 	
 build: | mkdir ${EMBED_MQTTLIB_C_TARGET} ${SYNC_SAMPLES} ${SYNC_TESTS}
 
+lib: | mkdir ${EMBED_MQTTLIB_C_TARGET}
+
 clean:
 	rm -rf ${blddir}/*
 	
